
plugins:
  # https://github.com/babel/eslint-plugin-babel
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true
  
# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  linebreak-style: 0
  indent: [2, "tab"]
  no-tabs: 0